fix(command-dev): allow netlify-lambda build parameters
netlify/cli pull request #1311
Opened 2020-10-01 16:43 UTC by sdegroot

**- Summary**

Having a Netlify project with the following package.json doesn't work (it doesn't find the functions)
`{
  "name": "project",
  "private": true,
  "scripts": {
    "start": "netlify dev",
    "build": "run-p build:**",
    "build:lambda": "netlify-lambda build --config config/webpack.functions.js src/lambda/",
  }
}`

**- Test plan**

See test cases.

**- Description for the changelog**

netlify-lambda build step in package.json now allows the use of command line arguments like --config. 

**- A picture of a cute animal (not mandatory but encouraged)**

2020-10-02 08:23 UTC, sdegroot commented
Not sure why these tests are failing, they seem to be failing on master as well. 

Both return the following output

```
  ✖ tests › command.deploy › should deploy edge handlers when directory exists Rejected promise returned by test

  1 test failed

  tests › command.deploy › should deploy edge handlers when directory exists

  /Users/sdegroot/scm/github/netlify-cli/node_modules/execa/lib/error.js:56

  Rejected promise returned by test. Reason:

  Error {
    command: '/Users/sdegroot/scm/github/netlify-cli/bin/run deploy --json',
    exitCode: 2,
    failed: true,
    isCanceled: false,
    killed: false,
    signal: undefined,
    signalDescription: undefined,
    stderr: ` ›   Warning: ␊
     ›   {␊
     ›     "oclif": {␊
     ›       "exit": 2␊
     ›     }␊
     ›   }␊
     ›␊
     ›`,
    stdout: '',
    timedOut: false,
    message: 'Command failed with exit code 2: /Users/sdegroot/scm/github/netlify-cli/bin/run deploy --json',
  }

  makeError (node_modules/execa/lib/error.js:56:11)
  handlePromise (node_modules/execa/index.js:114:26)
  callCli (tests/utils/callCli.js:5:22)
  tests/command.deploy.test.js:115:24
  withSiteBuilder (tests/utils/siteBuilder.js:127:12)
  tests/command.deploy.test.js:87:7

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! netlify-cli@2.64.1 test:ava: `nyc --reporter=lcov ava --verbose && nyc report`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the netlify-cli@2.64.1 test:ava script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sdegroot/.npm/_logs/2020-10-02T08_23_05_541Z-debug.log
ERROR: "test:ava" exited with 1.
npm ERR! Test failed.  See above for more details.
```

2020-10-05 10:18 UTC, erezrokah requested changes
Thanks @sdegroot, nice catch and fix.
Added a few comments.

Also the tests are failing since the CLI will load each JS file under `function-builder-detectors` as a detector:
https://github.com/netlify/cli/blob/693b33e68663419fa807907f2a001f8e97149f45/src/utils/detect-functions-builder.js#L4

Meaning the CLI tries to load the test file as a detector and fails.

I suggest moving it to a subdirectory.

2020-10-05 10:18 UTC, erezrokah commented on src/function-builder-detectors/netlify-lambda.js
> +    const match = script.match(/netlify-lambda build.* (\S+)\s*$/)
Could we switch to something like https://github.com/substack/node-shell-quote#parse?

2020-10-05 10:18 UTC, erezrokah commented on src/function-builder-detectors/netlify-lambda.js
> +    console.log(match)
Can we remove this log message?

2020-10-05 10:18 UTC, erezrokah commented on src/function-builder-detectors/netlify-lambda.js
> +module.exports = function(packageSettings) {
Instead of changing the API for the detector, can we extract the relevant part to a function and test only that function?

2020-10-28 10:06 UTC, sdegroot commented
Whoops, I forgot about this one. I'll try and have a look this weekend, apologies for the delay and thanks for the review!

2020-11-10 18:30 UTC, erezrokah approved these changes
Thanks @sdegroot, added a commit with some minor changes.

2020-11-10 18:43 UTC, merged