Add `func-style` ESLint rule
netlify/cli pull request #1421
Opened 2020-10-16 13:54 UTC by ehmicky

This adds the [`func-style`](https://eslint.org/docs/rules/func-style) ESLint rule.

2020-10-16 13:55 UTC, ehmicky commented on src/commands/functions/create.js
> -  function filterRegistry(registry, input) {
Those functions can be safely moved to the top-level scope.

2020-10-20 15:11 UTC, erezrokah requested changes
Should we enable https://eslint.org/docs/rules/func-style#allowarrowfunctions?

2020-10-20 20:42 UTC, ehmicky commented
That works :+1: 

Should we try to ensure consistency (`const myFunc = function(...){...}` vs `const myFunc = (...) => {...}`). Both styles are almost the same and work, but would it be useful to enforce consistency over one specific style?
If so, which ESLint rule would be the best to enforce this? I have struggled with this specific linting problem in my personal projects, but there might be a solution.

2020-10-21 11:38 UTC, erezrokah commented
> That option is always enabled when the rule is set to `expression` (the default),

Cool, didn't notice that.

I would also prefer to choose one of the two styles. Don't think it is a blocker for this PR (especially if we don't have built in support for it).

2020-10-22 14:06 UTC, ehmicky commented
Rebased. Ready for another review :+1:

2020-10-22 14:49 UTC, erezrokah approved these changes

2020-10-22 15:11 UTC, merged

2020-10-22 20:28 UTC, ehmicky commented
This is enforceable with `no-restricted-syntax`. However, enforcing arrow functions would also require writing:

```js
module.exports = {
  onBuild() {...}
}
```

As:

```js
module.exports = {
  onBuild: () => {...}
}
```

Which might be more verbose?

Also, this would not come with autofixing, so I am thinking this specific rule might be more of a nuisance than a help there, and leaving inconsistent style might be more practical. What do you think?

2020-10-25 11:05 UTC, erezrokah commented
> Also, this would not come with autofixing, so I am thinking this specific rule might be more of a nuisance than a help there, and leaving inconsistent style might be more practical. What do you think?

Agreed