Add `id-length` ESLint rule
netlify/cli pull request #1422
Opened 2020-10-16 14:25 UTC by ehmicky

This adds the [`id-length`](https://eslint.org/docs/rules/id-length) ESLint rule.
See also https://github.com/netlify/build/pull/1982

Single-letter variable names makes reading code less clear.

2020-10-20 16:03 UTC, erezrokah requested changes
This is huge @ehmicky thanks.
Added a few comments

2020-10-20 20:15 UTC, ehmicky commented
Answered this in the PR for Netlify Build, let's solve this first: https://github.com/netlify/build/pull/1982#issuecomment-713112437

2020-10-21 12:52 UTC, ehmicky commented on src/commands/dev/index.js
> -const getAddonsUrlsAndAddEnvVariablesToProcessEnv = async ({ api, site, flags }) => {
:+1:

2020-10-21 12:52 UTC, ehmicky commented on src/functions-templates/js/identity-signup/identity-signup.js
> +      custom_data_from_func: 'hurray this is some extra metadata',
Good point :+1:

2020-10-21 12:52 UTC, ehmicky commented
Thanks @erezrokah! 
I have removed the `max` constraint.
I also removed all the changes in this PR related to long variable names, so this PR is a little smaller.

2020-10-22 11:09 UTC, ehmicky commented
Rebased. Does this look good @erezrokah ?

2020-10-22 11:41 UTC, erezrokah approved these changes

2020-10-22 11:45 UTC, merged