feat(dev): set path to geoip location database
netlify/cli pull request #1524
Opened 2020-11-04 17:25 UTC by calavera

This will allow testing edge handlers to geoip location capabilities.

That flag was introduced in https://github.com/netlify/traffic-mesh/pull/1199/files

Signed-off-by: David Calavera <david.calavera@gmail.com>

2020-11-04 17:43 UTC, erezrokah requested changes
This looks good.
Does it need a version bump for the npm traffic mesh agent package?
I'm getting:
```
error: Found argument '--location-db' which wasn't expected, or isn't valid in this context
```
When passing the argument

2020-11-04 17:50 UTC, calavera commented
That's weird, I assumed that the most recent version had that option already, I'll double check.

2020-11-05 11:00 UTC, erezrokah commented on package-lock.json
> +          "resolved": "http://registry.npmjs.org/pify/-/pify-2.3.0.tgz",
Going to merge this once I figure out these `https->http` changes

2020-11-05 12:52 UTC, erezrokah requested changes
~~@calavera I'm still getting the same error with version `0.24.0`~~
~~Maybe it's because I'm submitting a wrong db?~~
Argument name should be `geo`

2020-11-05 15:07 UTC, merged