update fauna crud template
netlify/cli pull request #1853
Opened 2021-02-08 07:50 UTC by fireridlle

Update faunadb-js package version.
Rewrite FQL to modern style

2021-02-08 19:46 UTC, JGAntunes requested changes
Thanks for your contribution @fireridlle! 🙏 Just a small note and I think we're good to go 👍

2021-02-08 19:46 UTC, JGAntunes commented on src/functions-templates/js/fauna-crud/package.json
> +  "version": "2.0.0",
I don't believe bumping this version is required, as this is used for template purposes.

```suggestion
  "version": "1.0.0",
```

2021-02-08 20:26 UTC, fireridlle commented
@JGAntunes thank you. updated

2021-02-09 11:03 UTC, JGAntunes commented
Seems like our formatter is complaining - https://github.com/netlify/cli/pull/1853/checks?check_run_id=1857985371 - could you possibly fix these and push again? `npm run format:fix:prettier` should take care of it.

2021-02-09 16:27 UTC, JGAntunes approved these changes

2021-02-09 17:03 UTC, merged

2021-02-10 10:54 UTC, JGAntunes commented
Released under `v3.7.0`. Thanks @fireridlle 👍  - https://www.npmjs.com/package/netlify-cli/v/3.7.0