feat: add a prompt to modify users .gitignore (closes netlify#2038)
netlify/cli pull request #3595
Opened 2021-11-05 13:18 UTC by ngonsoto

🎉 Thanks for submitting a pull request! 🎉

#### Summary

Fixes #2038

Edits to .gitignore file are not shown to the user. This PR adds a prompt if the .netlify folder is not found in the .gitignore file and asks the user if it wants to add it.

---

For us to review and ship your PR efficiently, please perform the following steps:

- [ ] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [ ] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**
![8741538e4321434fe9f765f0769c78892](https://user-images.githubusercontent.com/27125998/140516177-9b325fff-dbfe-421a-b8c0-36f42f830f0d.jpg)

2021-12-07 14:33 UTC, lukasholzer requested changes
@ngonsoto Thank you very much for your PR and taking the time to enhance our CLI! 
I want to apologize upfront for being so late with my review 😬 

From a consumer perspective there is no reason why the `.netlify` folder should not be added to the `.gitignore`, or at least we don't want to promote it. As all our build outputs are there and they should not be committed.

So the user input here would be in 99% the cases a "yes" – I think we can drop it for a better user experience and instead providing a meaningful log message that we adapted the users `.gitignore` which is stated as solution inside the issue:

> Describe the solution you'd like
> 
> When the CLI modifies .gitignore we should print a log message reflecting the change to the user

Furthermore a prompt would cause issues on the link command in the CI so we would need to adapt it with a flag to pass without asking. The simpler and better approach in my humble opinion is to informing the user.

Therefore can you please update the PR with a log message?

2021-12-07 17:58 UTC, ngonsoto commented
Hi @lukasholzer, no problem. I'll be updating the PR with the requested changes.

2021-12-09 09:08 UTC, lukasholzer commented on src/utils/gitignore.js
> +    log('Adding local .netlify folder to .gitignore file...')
```suggestion
    log('Adding local .netlify folder to .gitignore file.')
```

2021-12-09 09:09 UTC, lukasholzer approved these changes
Awesome! Thank you very much for going over and adapting the PR 🌟

2021-12-13 10:39 UTC, merged