chore!: remove node 10 support
netlify/cli pull request #3648
Opened 2021-11-16 10:16 UTC by lukasholzer

🎉 Thanks for submitting a pull request! 🎉

#### Summary

Fixes #3512

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [x] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

![image](https://user-images.githubusercontent.com/11156362/141966729-0f56a0a7-9980-4b6c-9334-24133c257fcf.png)

2021-11-16 10:27 UTC, erezrokah requested changes
This is looking 🔥 @lukasholzer, answered your question about Edge Handlers and added a comment.

2021-11-16 10:27 UTC, erezrokah commented on src/functions-templates/javascript/google-analytics/package.json
> +    "netlify-cli": "latest",
What is the reason we need the CLI as a dependency for this function template?
Function templates are used for this command:
https://cli.netlify.com/commands/functions#functionscreate

to create a new function from a template.

2021-11-16 10:27 UTC, erezrokah commented on tests/command.deploy.test.js
> +  // TODO: check with erez if we should update edge handler min version to 12 so they can drop compatibility
For the CLI tests we should drop this condition (we should have dropped it a while back).

I suggest opening a new issue in https://github.com/netlify/netlify-plugin-edge-handlers to handle Node.js 10 deprecation

2021-11-16 10:27 UTC, erezrokah commented on tests/command.dev.test.js
> +  // TODO: check with erez if we should update edge handler min version to 12 so they can drop compatibility
Same as previous comment

2021-11-16 15:46 UTC, ehmicky commented
This is looking great to me too! :+1: 
Nothing to add except for what @erezrokah mentioned, with one exception: the CI tests are currently failing, which might indicate some problem.

2021-11-17 09:23 UTC, lukasholzer commented
> This is looking great to me too! 👍 Nothing to add except for what @erezrokah mentioned, with one exception: the CI tests are currently failing, which might indicate some problem.

Yea currently figuring out why the tests are failing – therefore I set the PR in the draft state. This should indicate that it is not ready for review – I try to create always fast PR's so that folks that are interested can already see in which direction it turns, fast feedback. 

But it is strange that it is failing as my changes should not influence that

2021-11-17 11:10 UTC, lukasholzer commented
The `build (ubuntu-latest, 10.x)` is hanging around as there is now a new `Testing for CLI / build (ubuntu-latest, 12.x)` that we need to add as required status checks once this PR is merged

2021-11-17 12:09 UTC, erezrokah approved these changes

2021-11-17 12:10 UTC, erezrokah commented
> The `build (ubuntu-latest, 10.x)` is hanging around as there is now a new `Testing for CLI / build (ubuntu-latest, 12.x)` that we need to add as required status checks once this PR is merged

I updated the branch protections settings, so this should be fixed now

2021-11-17 12:12 UTC, erezrokah commented
> I updated the branch protections settings, so this should be fixed now

You should be able to do it too I think as you're a part of https://github.com/orgs/netlify/teams/netlify-dev

2021-11-17 13:35 UTC, ehmicky approved these changes
:tada:

2021-11-18 14:29 UTC, merged