fix: npm run docs on Windows (#3973)
netlify/cli pull request #4319
Opened 2022-02-16 22:23 UTC by iib0011

#### Summary

Fixes #3973

2022-02-17 12:15 UTC, erezrokah requested changes
Thanks @iib0011, I left a comment

2022-02-17 12:36 UTC, iib0011 commented on site/scripts/docs.mjs
> +const markdownFiles = [
No, it wouldn't since there is a condition on the platform

2022-02-17 12:39 UTC, erezrokah commented on site/scripts/docs.mjs
> +const markdownFiles = [
It the condition required? Will it work for all platforms without the condition?

2022-02-17 12:48 UTC, iib0011 commented on site/scripts/docs.mjs
> +const markdownFiles = [
the condition is required for windows users

2022-02-17 12:50 UTC, erezrokah commented on site/scripts/docs.mjs
> +const markdownFiles = [
Thanks for the additional information, let me clarify as I had a typo:
1. For windows, running `normalizeBackslash` will fix the issue
2. For non-windows, running `normalizeBackslash` will not have an impact, so we can keep it

Is that correct?

2022-02-17 13:29 UTC, iib0011 commented on site/scripts/docs.mjs
> +const markdownFiles = [
I see now. Let me correct it

2022-02-17 13:48 UTC, iib0011 commented on site/scripts/docs.mjs
> +const markdownFiles = [
fixed

2022-02-17 14:04 UTC, erezrokah commented on site/scripts/docs.mjs
> +const markdownFiles = [
Added another commit in https://github.com/netlify/cli/pull/4319/commits/2011c3101ff3bbe88e74b1ccbdb212c8fdaddadb.

Can you let me know if that works for you on Windows?

2022-02-17 16:29 UTC, merged

2022-02-20 11:01 UTC, iib0011 commented on site/scripts/docs.mjs
> +const markdownFiles = [
Yes it works