feat(sites): Repo shorthand for create:site-template
netlify/cli pull request #4382
Opened 2022-02-25 21:49 UTC by iib0011

#### Summary

Fixes #4326

We can now use:

`ntl sites:create-template nextjs-blog-theme`
which will expand to github.com/netlify-templates/nextjs-blog-theme

And this:

`ntl sites:create-template jlengstorf/my-template`
which will expand to github.com/jlengstorf/my-template

2022-02-28 13:36 UTC, erezrokah requested changes
Thanks @iib0011, very cool 🚀 

Can we declare the repo as an "official" optional command argument? See https://github.com/tj/commander.js/tree/02a124c7d58dbae2ef11f9284b2c68ad94f6dc8b#command-arguments

That should add it to the help and docs and allow better access to it in the command action

2022-02-28 14:01 UTC, iib0011 commented
Ok. Let me change it

On Mon, Feb 28, 2022 at 2:36 PM Erez Rokah ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks @iib0011 <https://github.com/iib0011>, very cool 🚀
>
> Can we declare the repo as an "official" optional command argument? See
> https://github.com/tj/commander.js/tree/02a124c7d58dbae2ef11f9284b2c68ad94f6dc8b#command-arguments
>
> That should add it to the help and docs and allow better access to it in
> the command action
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/netlify/cli/pull/4382#pullrequestreview-895090549>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOBJ6LA2T3F5YIQKPTUB2FTU5N257ANCNFSM5PLLZ5ZA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-28 17:06 UTC, erezrokah commented
> Ok. Let me change it
> […](#)

Thanks, it seems this PR has some unnecessary changes (e.g. types and line removals). Do you mind reverting them?

2022-02-28 17:53 UTC, iib0011 commented
Okay

2022-03-02 13:27 UTC, erezrokah approved these changes

2022-03-02 13:38 UTC, erezrokah commented
@iib0011, I added a few commits, specifically https://github.com/netlify/cli/pull/4382/commits/b9632a40ab9b315554b49c31031fafb9bbcfa41e to handle non existing/non template repositories.

Please let me know what you think

2022-03-02 14:00 UTC, merged