fix: stop pass through request params for function redirects
netlify/cli pull request #4897
Opened 2022-08-03 14:49 UTC by tinfoil-knight

🎉 Thanks for submitting a pull request! 🎉

#### Summary

Note: PR is not ready for review. I need to cleanup the description & minimal reproduction before that.

Fixes #4273 

Query parameters specified in function redirects are not being passed (they're over-written by the request parameters).

This was due to an intentional change in https://github.com/netlify/cli/issues/1605 to match production behaviour at that time.

Production behaviour has changed now. 

Minimal reproduction of the issue: https://github.com/KK-Learning-Gym/4273-with-fn

Deployed Project Link: `https://with-fn-testing.netlify.app/api/test?foo=1&foo=2&bar=1&bar=2`

---

For us to review and ship your PR efficiently, please perform the following steps:

- [ ] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [ ] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**
🦁

2022-08-03 15:59 UTC, tinfoil-knight commented
Note: I confirmed w/ https://github.com/eric-silverman on Slack for approval to create the PR for the attached issue.

2022-08-10 17:47 UTC, danez requested changes
LGTM 🎉

Can we add an additional assertion that tests the `:splat` behavior with functions?

2022-08-10 17:52 UTC, tinfoil-knight commented
> Can we add an additional assertion that tests the `:splat` behavior with functions?

Yeah. I'll add a test-case.

2022-08-10 19:36 UTC, tinfoil-knight commented on tests/integration/200.command.dev.test.js
> +            { from: '/baz/*', to: '/.netlify/functions/echo?query=:splat' },
Small note here:

The redirects rules were using template literal strings instead of conventional ones so I've changed them.

2022-08-11 09:07 UTC, danez approved these changes

2022-08-15 09:57 UTC, danez commented
Feel free to merge. You can also use kodiak for merging, by simply adding the `automerge` label.

2022-08-15 10:12 UTC, tinfoil-knight commented
@danez I don't have access to merge or add any labels yet.

2022-08-15 10:13 UTC, danez commented
Oh I see, I can merge if you want?

2022-08-15 10:14 UTC, tinfoil-knight commented
> Oh I see, I can merge if you want?

Yeah. Please do.

2022-08-15 10:27 UTC, merged