fix: add zsh autocomplete setup and file permissions instructions to completion:install
netlify/cli pull request #6882
Opened 2024-10-17 15:55 UTC by benhancock

🎉 Thanks for submitting a pull request! 🎉

#### Summary

Fixes [Completions don't work](https://github.com/netlify/cli/issues/6724)

There are at least two issues that might cause `completion:install` to fail:

1. On Linux/MacOS, the completion script may not have the necessary executable permissions.
- **Fix:** Run `chmod +x` with the file path to the completion script

2. Netlify uses [Tabtab](https://github.com/denosaurs/tabtab) for completions, and with zsh, Tabtab (and other) completions do not work until [compinit](https://github.com/zsh-users/zsh/blob/master/Completion/compinit) has been run. 
- **Fix:** Add the line `autoload -U compinit; compinit` to the user’s `~/.zshrc` file above the Tabtab config line to load and then run `compinit`

This PR addresses both of these issues by:
1. automatically outputting the `chmod +x` command with the appropriate file path for the user to copy and run if needed after the installation is complete;
2. prompting the user to have the `autoload -U compinit; compinit` line added to the top of their .zshrc file automatically if not already present.

Here's what the `netlify completion:install` output looks like before:

![Screenshot 2024-10-17 at 11 44 44 AM](https://github.com/user-attachments/assets/96f365b6-0ca0-414f-aaa9-d53db9911c00)

Here's what the `netlify completion:install` output looks like after our changes:

![Screenshot 2024-10-17 at 11 45 41 AM](https://github.com/user-attachments/assets/a4751503-62f8-4b31-b668-4e58d2c15fa0)

---

For us to review and ship your PR efficiently, please perform the following steps:

- [ ] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [ ] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and
      passes our tests.
- [ ] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

2024-10-17 16:02 UTC, dylanspyer commented
We decided not to modify file permissions on the user's behalf and instead output the `chmod` command for the user to run manually. This ensures that the user maintains ownership of their security and configuration settings.

2024-10-17 16:16 UTC, benhancock commented on src/commands/completion/completion.ts
> +    log("\nTo ensure proper functionality, you'll need to set appropriate file permissions.")
Because `chmod` is a Unix command, we only output this instruction if the user is not on windows

2024-10-19 16:15 UTC, DanielSLew requested changes
Looks great! Just a few changes that I've requested

2024-10-19 16:15 UTC, DanielSLew commented on src/commands/completion/completion.ts
> +  const AUTOLOAD_COMPINIT = 'autoload -U compinit; compinit'
Throw these in the constants file in this folder

2024-10-19 16:15 UTC, DanielSLew commented on src/commands/completion/completion.ts
> +      .then((answer) => {
Generally you wouldn't use `await` and `.then()` you would use one or the other. If you want it to be blocking use `await`, if you want it to not be blocking use `.then()`

```suggestion
    const answer = await inquirer
      .prompt([
        {
          type: 'confirm',
          name: 'compinitAdded',
          message: `Would you like to add it?`,
          default: true,
        },
      ])
```

2024-10-19 16:15 UTC, DanielSLew commented on src/commands/completion/completion.ts
> +          fs.readFile(zshConfigFilepath, 'utf8', (err, data) => {
I would await this. So await fs.readFile or use fs.readFileSync.

2024-10-19 16:15 UTC, DanielSLew commented on src/utils/command-helpers.ts
> +    // @ts-expect-error TS(2571) FIXME: Object is of type 'unknown'.
Pull in the main branch to get updates from this PR https://github.com/netlify/cli/pull/6877 to fix this type error

2024-10-19 16:15 UTC, DanielSLew commented on tests/integration/commands/completion/completion-install.test.ts
> +const AUTOLOAD_COMPINIT = 'autoload -U compinit; compinit'
pull these from `constants` when you make the change from above

2024-10-25 18:59 UTC, DanielSLew requested changes

2024-10-25 18:59 UTC, DanielSLew commented on tests/integration/commands/completion/completion-install.test.ts
> +const AUTOLOAD_COMPINIT = 'autoload -U compinit; compinit'
Use the exports you created in the other file already

2024-10-28 20:14 UTC, DanielSLew approved these changes

2024-10-28 20:24 UTC, merged